### PR TITLE
Mat steel

### PR DESCRIPTION
**Pull request by HughGrovesArup**
Hi @nic-burgers-arup this pull request fixes a bug in MAT_STEEL that I identified.

During testing the ModelValidationTests shows a problem with the NODE.3 in the stream. It seems like all of the nodes in the stream are being assigned the same index and are being overwritten. The logic for this was quite convoluted - would you be able to take a look and see if its a real problem?

image

### CODE REVIEW

**Comment by nic-burgers-arup** [comment]
Hi @HughGrovesArup, regarding the node issue, the reason for what you're seeing is that the coordinate values in the test file are in millimetres, which are within GSA's tolerance for node resolution.  In short, the shapes are so small to GSA that thinks all the nodes are the same one so it always gives back the same index.

**Review by nic-burgers-arup — CHANGES_REQUESTED** [review]
The GWA-related changes look fine, but due to the move to the NB folder the standard receiver tests - not the ones for debug - are now unable to find their test data since some have moved to the NB folder.

Could you make the necessary changes so that all the tests pass?

By the way, I have a version of the gMu-Xgpc.json file that has its coordinates (vertices and values) multiplied by 1000 to express them in metres - happy to send this over to you to ensure the model validation tests work too.

**Comment by HughGrovesArup** [comment]
d'oh - thanks @nic-burgers-arup! Yes please do send through that file, then I'll get all of the tests completing succesfully.

**Comment by HughGrovesArup** [comment]
@nic-burgers-arup - tests have now been updated and run

**Review by nic-burgers-arup — APPROVED** [review]

**Pull request merged**
